name: day1
channels:
  - conda-forge
  - defaults
dependencies:
  - certifi=2019.9.11
  - pip=19.2.3
  - python=3.6.7
  - setuptools=41.2.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.33.6
  - wincertstore=0.2
  - pip:
      - azure-functions
      - azure-storage==0.36.0
      - azure-functions-worker==1.0.0b11
      - singleton-decorator==1.0.0
      - applicationinsights==0.11.9
      - numpy==1.18.1
      - matplotlib==3.1.3
      - pillow==6.1.0
